{
 "title": "Top 5 High-Frequency Grafana Visualizations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage (Time Series)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "millicores" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*\"}[5m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Working Set (Gauge)",
   "type": "gauge",
   "description": "Current working set memory per container or node. ",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_app=\"node-exporter\"} /1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods (Stat)",
   "type": "stat",
   "description": "Shows the total number of Pods running. ",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bar Gauge (Ranked Comparative View)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, container_memory_working_set_bytes) / 1024 / 1024",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Table Panel (Detailed Multi-Dimension Metrics)",
   "type": "table",
   "description": "Per-container network TX with labels: pod name, container name, namespace, etc. ",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": " rate(container_network_transmit_bytes_total[5m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}